# Generated by Django 5.1.4 on 2025-01-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaklog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
