# Generated by Django 5.1.4 on 2025-01-16 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_breaklog_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinglog',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.shift'),
        ),
    ]
