# Generated by Django 5.1.4 on 2025-01-20 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_packinglog_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packing',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductPacking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.packing')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
            ],
        ),
    ]
