# Generated by Django 5.1.4 on 2025-01-28 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_shift_user_ends_shift_user_starts'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_duration_in_minute', models.IntegerField(default=480)),
            ],
        ),
        migrations.RemoveField(
            model_name='shift',
            name='packing',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='ready_value',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='shift_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='target_value',
        ),
        migrations.AddField(
            model_name='packing',
            name='norm',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ShiftTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('target', models.PositiveIntegerField()),
                ('ready_value', models.PositiveIntegerField(blank=True, null=True)),
                ('time_spent', models.PositiveBigIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.packing')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.shift')),
            ],
        ),
    ]
