# Generated by Django 5.1.4 on 2025-01-31 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_shifttask_percent_from_shift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifttask',
            name='status',
        ),
        migrations.AddField(
            model_name='shifttask',
            name='remaining_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='type',
            field=models.CharField(choices=[('TASK', 'Task'), ('BREAK', 'Break')], default='TASK', max_length=120),
        ),
        migrations.AlterField(
            model_name='shifttask',
            name='packing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.packing'),
        ),
        migrations.AlterField(
            model_name='shifttask',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product'),
        ),
        migrations.AlterField(
            model_name='shifttask',
            name='target',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
