# Generated by Django 5.1.4 on 2025-02-27 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0008_remove_shifttask_status_shifttask_remaining_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='dashboard.shifttask'),
        ),
        migrations.AlterField(
            model_name='packinglog',
            name='sid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
