# Generated by Django 5.1.4 on 2025-03-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0009_packinglog_task_alter_packinglog_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='active_task',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
