# Generated by Django 5.1.4 on 2025-03-23 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0010_shift_active_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shifttask',
            old_name='time_needed_in_minute',
            new_name='time_needed',
        ),
    ]
